require('pry-byebug')
require_relative('models/customer.rb')
require_relative('models/film.rb')
require_relative('models/ticket.rb')
require_relative('models/screening.rb')

Ticket.delete_all()
Screening.delete_all()
Customer.delete_all()
Film.delete_all()

customer1 = Customer.new({'name' => 'Penny', 'funds' => 20})
customer1.save()
customer2 = Customer.new({'name' => 'Pierre', 'funds' => 50})
customer2.save()
customer3 = Customer.new({'name' => 'Marnie', 'funds' => 40})
customer3.save()
customer4 = Customer.new({'name' => 'Lewis', 'funds' => 30})
customer4.save()

film1 = Film.new({'title' => 'John Wick', 'price' => 10})
film1.save()
film2 = Film.new({'title' => 'Fifth Element', 'price' => 20})
film2.save()
film3 = Film.new({'title' => 'Gladiator', 'price' => 30})
film3.save()

ticket1 = Ticket.new({'customer_id' => customer1.id, 'film_id' => film2.id})
ticket1.save()
ticket2 = Ticket.new({'customer_id' => customer3.id, 'film_id' => film1.id})
ticket2.save()
ticket3 = Ticket.new({'customer_id' => customer2.id, 'film_id' => film3.id})
ticket3.save()
ticket4 = Ticket.new({'customer_id' => customer4.id, 'film_id' => film1.id})
ticket4.save()
ticket5 = Ticket.new({'customer_id' => customer2.id, 'film_id' => film2.id})
ticket5.save()
ticket6 = Ticket.new({'customer_id' => customer3.id, 'film_id' => film2.id})
ticket6.save()

screening1 = Screening.new({'film_id' => film1.id, 'show_time' => '21:00'})
screening1.save()
screening2 = Screening.new({'film_id' => film2.id, 'show_time' => '19:00'})
screening2.save()
screening3 = Screening.new({'film_id' => film3.id, 'show_time' => '20:00'})
screening3.save()
screening4 = Screening.new({'film_id' => film3.id, 'show_time' => '21:00'})
screening4.save()

binding.pry
nil
